#!/usr/bin/env bash
#
# provision/start.sh
#
# @author  Denis Luchkin-Zhou <wyvernzora@gmail.com>
# @license MIT
#


#
# Get rid of CDPATH, then make sure we are in the provisioning root
#
unset CDPATH
ROOT="$( dirname $(dirname "${BASH_SOURCE[0]}") )"
cd "${ROOT}"


#
# Global configuration
#
BB_LOG_LEVEL=1
BB_LOG_USE_COLOR=true
BB_WORKSPACE='.bb-workspace'


#
# Boolean values
#
TRUE=0
FALSE=1


#
# Load bash booster
#
source .provision/bashbooster



#
# Ask for admin password in advance
#
bb-log-info "Some provisioning operation will require root access"
sudo -v



#
# Keep refreshing sudo timestamp until provisioner exits
#
while true; do
  sudo -n true
  sleep 60
  kill -0 "$$" || exit
done 2> /dev/null &



#
# Load utilities
#
for util in .provision/u-*.sh; do
  source $util
  bb-log-debug "Loaded $util"
done



#
# Load all package provisioning tasks
#
provision_all=""

for package in $(find -H '.' -maxdepth 3 -name '.provision.sh'); do
  task_name="$(basename $(dirname "$package") ".symlink")-provision";
  source $package
  provision_all="${provision_all} ${task_name}"
  bb-log-debug "Loaded $task_name"
done


#
# Hello World
#
bb-log-debug 'Debug'
bb-log-info "Hello World"
bb-log-warning "Warning"
bb-log-error "Error"


#
# Start the task
#
if [ -z "$1" ]; then
  bb-task-run $provision_all
else
  bb-task-run "$1-provision"
fi
